name: fmle_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.4
  - numpy=2.0.0
  - pandas=2.2.2
  - scipy=1.14.0
  - statsmodels=0.14.5
  - seaborn=0.13.2
  - scikit-learn=1.5.0
  - pip
  - pip:
      - ray==2.48.0
      - matplotlib==3.9.0
      - openpyxl
